stages:
    - build
    - test

build:
    stage: build
    before_script:
      - cd ZsutPw.Sdn.ControlSvc
    script:
      - dotnet restore
      - dotnet build -c Debug
      - dotnet build -c Release
    tags:
      - all, integration

test:
    stage: test
    before_script:
      - cd ZsutPw.Sdn.ControlSvc.Tests
    script:
      - dotnet restore
      - dotnet build -c Debug
      - dotnet build -c Release
      - dotnet test
    tags:
      - all, integration

