#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
LABEL stage=zsutpw-sdn-controlsvc_dev_build
WORKDIR /src
COPY . .
WORKDIR "/src/ZsutPw.Sdn.ControlSvc"
RUN dotnet restore
RUN dotnet build -c Debug -o /app/build
RUN dotnet publish -c Debug -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
EXPOSE 80
EXPOSE 443
#RUN dotnet dev-certs https
#RUN dotnet dev-certs https --trust'
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "ZsutPw.Sdn.ControlSvc.dll"]
